import type { QwikIntrinsicElements } from "@builder.io/qwik";

/***************************************************
 * Generated by SVG Artista on 5/24/2023, 9:52:54 AM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

//  svg .svg-elem-1 {
//   stroke-dashoffset: 336.3434753417969px;
//   stroke-dasharray: 336.3434753417969px;
//   -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s;
//           transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s;
// }

// svg.active .svg-elem-1 {
//   stroke-dashoffset: 0;
// }

// svg .svg-elem-2 {
//   stroke-dashoffset: 900.15771484375px;
//   stroke-dasharray: 900.15771484375px;
//   -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s;
//           transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s;
// }

// svg.active .svg-elem-2 {
//   stroke-dashoffset: 0;
// }

// svg .svg-elem-3 {
//   stroke-dashoffset: 479.57672119140625px;
//   stroke-dasharray: 479.57672119140625px;
//   -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s;
//           transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s;
// }

// svg.active .svg-elem-3 {
//   stroke-dashoffset: 0;
// }


export function HUDMiddleLeft(
  props: QwikIntrinsicElements["svg"],
  key: string
) {
  return (
    <svg
      viewBox="0 0 271 649"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
      key={key}
    >
      <g filter="url(#filter0_d_27_91)">
        <path
          d="M207.126 599.521C175.119 584.392 146.035 562.217 121.534 534.259M44.25 321.342C44.25 281.798 51.0757 242.642 64.3367 206.109M121.534 108.426C146.035 80.4681 175.119 58.2927 207.126 43.1642"
          stroke="#73E5FE"
          class="svg-elem-1"
        ></path>
      </g>
      <g filter="url(#filter1_d_27_91)">
        <path
          d="M258.428 637.364C214.933 632.047 188.284 615.537 188.284 615.537C155.209 599.371 125.156 575.676 99.8395 545.802C74.523 515.928 60.8685 497.367 47.166 458.332L25.4184 453.014C-5.65126 344.744 -3.2707 285.54 25.4184 181.805L51.8262 171.17C65.5287 132.134 74.523 120.663 99.8395 90.7896C125.156 60.9158 155.21 37.2203 188.284 21.0544C188.284 21.0544 210.272 6.31781 258.428 1"
          stroke="#73E5FE"
          class="svg-elem-2"
        ></path>
      </g>
      <g filter="url(#filter2_d_27_91)">
        <path
          d="M85.7739 107C69.4968 128.258 63.1673 140.074 53.8438 166.192C52.8409 169.001 50.652 171.245 47.8498 172.268C40.8267 174.832 34.8512 176.98 28.805 179.725C26.2175 180.9 24.3312 183.243 23.5877 185.986C-3.95759 287.594 -6.14489 347.636 22.8344 447.919C23.434 449.993 24.6607 451.927 26.5554 452.964C30.3377 455.033 33.728 455.11 41.0498 455.893C44.8588 456.3 48.0239 458.963 49.2494 462.593C57.8643 488.106 65.5011 504.6 84.2731 526.644"
          stroke="#73E5FE"
          stroke-width="2.5"
          stroke-linecap="round"
          class="svg-elem-3"
        ></path>
      </g>
      <defs>
        <filter
          id="filter0_d_27_91"
          x="43.75"
          y="42.7122"
          width="175.59"
          height="568.26"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood flood-opacity="0" result="BackgroundImageFix"></feFlood>
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          ></feColorMatrix>
          <feOffset dx="10" dy="9"></feOffset>
          <feGaussianBlur stdDeviation="1"></feGaussianBlur>
          <feComposite in2="hardAlpha" operator="out"></feComposite>
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.0708333 0 0 0 0 0.14875 0 0 0 0 0.85 0 0 0 0.5 0"
          ></feColorMatrix>
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_27_91"
          ></feBlend>
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_27_91"
            result="shape"
          ></feBlend>
        </filter>
        <filter
          id="filter1_d_27_91"
          x="2.49998"
          y="0.503052"
          width="267.988"
          height="648.358"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood flood-opacity="0" result="BackgroundImageFix"></feFlood>
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          ></feColorMatrix>
          <feOffset dx="10" dy="9"></feOffset>
          <feGaussianBlur stdDeviation="1"></feGaussianBlur>
          <feComposite in2="hardAlpha" operator="out"></feComposite>
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.0708333 0 0 0 0 0.14875 0 0 0 0 0.85 0 0 0 0.5 0"
          ></feColorMatrix>
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_27_91"
          ></feBlend>
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_27_91"
            result="shape"
          ></feBlend>
        </filter>
        <filter
          id="filter2_d_27_91"
          x="0.75"
          y="105.75"
          width="98.274"
          height="433.144"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood flood-opacity="0" result="BackgroundImageFix"></feFlood>
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          ></feColorMatrix>
          <feOffset dx="10" dy="9"></feOffset>
          <feGaussianBlur stdDeviation="1"></feGaussianBlur>
          <feComposite in2="hardAlpha" operator="out"></feComposite>
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.0708333 0 0 0 0 0.14875 0 0 0 0 0.85 0 0 0 0.5 0"
          ></feColorMatrix>
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_27_91"
          ></feBlend>
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_27_91"
            result="shape"
          ></feBlend>
        </filter>
      </defs>
    </svg>
  );
}
