import type { QwikIntrinsicElements } from "@builder.io/qwik";

/***************************************************
 * Generated by SVG Artista on 5/24/2023, 9:56:04 AM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

//  svg .svg-elem-1 {
//   stroke-dashoffset: 889.5537109375px;
//   stroke-dasharray: 889.5537109375px;
//   -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s;
//           transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s;
// }

// svg.active .svg-elem-1 {
//   stroke-dashoffset: 0;
// }

// svg .svg-elem-2 {
//   stroke-dashoffset: 900.158447265625px;
//   stroke-dasharray: 900.158447265625px;
//   -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s;
//           transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s;
// }

// svg.active .svg-elem-2 {
//   stroke-dashoffset: 0;
// }

// svg .svg-elem-3 {
//   stroke-dashoffset: 479.57769775390625px;
//   stroke-dasharray: 479.57769775390625px;
//   -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s;
//           transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s;
// }

// svg.active .svg-elem-3 {
//   stroke-dashoffset: 0;
// }

// svg .svg-elem-4 {
//   stroke-dashoffset: 127.82252502441406px;
//   stroke-dasharray: 127.82252502441406px;
//   -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s;
//           transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s;
// }

// svg.active .svg-elem-4 {
//   stroke-dashoffset: 0;
// }

// svg .svg-elem-5 {
//   stroke-dashoffset: 222.1090850830078px;
//   stroke-dasharray: 222.1090850830078px;
//   -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s;
//           transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s;
// }

// svg.active .svg-elem-5 {
//   stroke-dashoffset: 0;
// }


export function HUDMiddleRight(
  props: QwikIntrinsicElements["svg"],
  key: string
) {
  return (
    <svg
      width="578"
      height="649"
      viewBox="0 0 578 649"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
      key={key}
    >
      <g filter="url(#filter0_d_27_78)">
        <path
          d="M264.077 15.3165C298.681 15.3165 332.947 23.0939 364.922 38.2069C396.896 53.3201 425.953 75.4739 450.432 103.407C474.911 131.341 494.332 164.506 507.583 201.011C520.834 237.516 527.654 276.643 527.654 316.159C527.654 355.675 520.834 394.802 507.583 431.307C494.332 467.812 474.911 500.977 450.432 528.911C425.953 556.844 396.896 578.998 364.921 594.111C332.947 609.224 298.681 617.001 264.077 617.001"
          stroke="#73E5FE"
          class="middleRight1"
        ></path>
      </g>
      <g filter="url(#filter1_d_27_78)">
        <path
          d="M307.572 0.63562C351.067 5.95343 377.716 22.4626 377.716 22.4626C410.791 38.6285 440.844 62.3241 466.161 92.1979C491.477 122.072 505.132 140.633 518.834 179.668L540.582 184.986C571.651 293.256 569.271 352.46 540.582 456.195L514.174 466.83C500.471 505.866 491.477 517.337 466.16 547.21C440.844 577.084 410.79 600.78 377.716 616.946C377.716 616.946 355.728 631.682 307.572 637"
          stroke="#73E5FE"
          class="middleRight2"
        ></path>
      </g>
      <g filter="url(#filter2_d_27_78)">
        <path
          d="M479.999 530.644C496.276 509.386 502.606 497.57 511.929 471.452C512.932 468.642 515.121 466.399 517.923 465.376C524.946 462.812 530.922 460.663 536.968 457.919C539.556 456.744 541.442 454.401 542.185 451.658C569.731 350.05 571.918 290.007 542.939 189.725C542.339 187.65 541.112 185.717 539.218 184.68C535.435 182.611 532.045 182.533 524.723 181.751C520.914 181.344 517.749 178.681 516.524 175.051C507.909 149.537 500.272 133.043 481.5 111"
          stroke="#73E5FE"
          stroke-width="2.5"
          stroke-linecap="round"
          class="middleRight3"
        ></path>
      </g>
      <g filter="url(#filter3_d_27_78)">
        <path
          d="M264.077 27.2247V15.5001C300.604 14.8209 329.002 18.3363 373.5 42"
          stroke="#73E5FE"
          stroke-width="2"
          stroke-linecap="round"
          class="middleRight4"
        ></path>
      </g>
      <g filter="url(#filter4_d_27_78)">
        <path
          d="M510 208.5C522.5 235.5 545.5 335 510 424"
          stroke="#73E5FE"
          stroke-width="2"
          stroke-linecap="round"
          class="middleRight5"
        ></path>
      </g>
      <defs>
        <filter
          id="filter0_d_27_78"
          x="264.077"
          y="14.8165"
          width="276.077"
          height="613.685"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood flood-opacity="0" result="BackgroundImageFix"></feFlood>
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          ></feColorMatrix>
          <feOffset dx="10" dy="9"></feOffset>
          <feGaussianBlur stdDeviation="1"></feGaussianBlur>
          <feComposite in2="hardAlpha" operator="out"></feComposite>
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.0708333 0 0 0 0 0.14875 0 0 0 0 0.85 0 0 0 0.5 0"
          ></feColorMatrix>
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_27_78"
          ></feBlend>
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_27_78"
            result="shape"
          ></feBlend>
        </filter>
        <filter
          id="filter1_d_27_78"
          x="307.512"
          y="0.139282"
          width="267.988"
          height="648.358"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood flood-opacity="0" result="BackgroundImageFix"></feFlood>
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          ></feColorMatrix>
          <feOffset dx="10" dy="9"></feOffset>
          <feGaussianBlur stdDeviation="1"></feGaussianBlur>
          <feComposite in2="hardAlpha" operator="out"></feComposite>
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.0708333 0 0 0 0 0.14875 0 0 0 0 0.85 0 0 0 0.5 0"
          ></feColorMatrix>
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_27_78"
          ></feBlend>
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_27_78"
            result="shape"
          ></feBlend>
        </filter>
        <filter
          id="filter2_d_27_78"
          x="478.749"
          y="109.75"
          width="98.274"
          height="433.144"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood flood-opacity="0" result="BackgroundImageFix"></feFlood>
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          ></feColorMatrix>
          <feOffset dx="10" dy="9"></feOffset>
          <feGaussianBlur stdDeviation="1"></feGaussianBlur>
          <feComposite in2="hardAlpha" operator="out"></feComposite>
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.0708333 0 0 0 0 0.14875 0 0 0 0 0.85 0 0 0 0.5 0"
          ></feColorMatrix>
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_27_78"
          ></feBlend>
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_27_78"
            result="shape"
          ></feBlend>
        </filter>
        <filter
          id="filter3_d_27_78"
          x="263.077"
          y="14.4247"
          width="123.423"
          height="39.5756"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood flood-opacity="0" result="BackgroundImageFix"></feFlood>
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          ></feColorMatrix>
          <feOffset dx="10" dy="9"></feOffset>
          <feGaussianBlur stdDeviation="1"></feGaussianBlur>
          <feComposite in2="hardAlpha" operator="out"></feComposite>
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.0708333 0 0 0 0 0.14875 0 0 0 0 0.85 0 0 0 0.5 0"
          ></feColorMatrix>
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_27_78"
          ></feBlend>
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_27_78"
            result="shape"
          ></feBlend>
        </filter>
        <filter
          id="filter4_d_27_78"
          x="509"
          y="207.5"
          width="32.9379"
          height="228.5"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood flood-opacity="0" result="BackgroundImageFix"></feFlood>
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          ></feColorMatrix>
          <feOffset dx="10" dy="9"></feOffset>
          <feGaussianBlur stdDeviation="1"></feGaussianBlur>
          <feComposite in2="hardAlpha" operator="out"></feComposite>
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.0708333 0 0 0 0 0.14875 0 0 0 0 0.85 0 0 0 0.5 0"
          ></feColorMatrix>
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_27_78"
          ></feBlend>
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_27_78"
            result="shape"
          ></feBlend>
        </filter>
      </defs>
    </svg>
  );
}
