import type { QwikIntrinsicElements } from "@builder.io/qwik";

/***************************************************
 * Generated by SVG Artista on 5/24/2023, 9:48:52 AM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

//  svg .svg-elem-1 {
//   stroke-dashoffset: 1853.55029296875px;
//   stroke-dasharray: 1853.55029296875px;
//   -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s;
//           transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s;
// }

// svg.active .svg-elem-1 {
//   stroke-dashoffset: 0;
// }


export function HUDRight(props: QwikIntrinsicElements["svg"], key: string) {
  return (
    <svg
      viewBox="0 0 223 845"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
      key={key}
    >
      <g filter="url(#filter0_d_23_50)">
        <path
          d="M1.5 1H166.672C167.202 1 167.711 1.21071 168.086 1.58579L183.414 16.9142C183.789 17.2893 184 17.798 184 18.3284V58.1299C184 58.6849 184.231 59.2148 184.637 59.5931L205.363 78.9069C205.769 79.2852 206 79.8151 206 80.3701V422.196C206 422.712 205.801 423.208 205.444 423.58L195.056 434.42C194.699 434.792 194.5 435.288 194.5 435.804V619.707C194.5 620.216 194.694 620.707 195.044 621.078L209.956 636.922C210.306 637.293 210.5 637.784 210.5 638.293V766.332C210.5 766.766 210.359 767.187 210.099 767.534L162.6 830.702C162.222 831.204 161.63 831.5 161.002 831.5H1M159.5 14.5L169.914 24.9142C170.289 25.2893 170.5 25.798 170.5 26.3284V64.2C170.5 64.7136 170.698 65.2074 171.052 65.5793L189.948 85.4207C190.302 85.7926 190.5 86.2864 190.5 86.8V414.72C190.5 415.222 190.311 415.705 189.972 416.074L179.528 427.426C179.189 427.795 179 428.278 179 428.78V626.19C179 626.71 179.202 627.209 179.564 627.582L194.5 643"
          stroke="#73E5FE"
          stroke-width="2"
          stroke-linecap="round"
          class="svg-elem-1"
        ></path>
      </g>
      <defs>
        <filter
          id="filter0_d_23_50"
          x="0"
          y="0"
          width="222.5"
          height="844.5"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood flood-opacity="0" result="BackgroundImageFix"></feFlood>
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          ></feColorMatrix>
          <feOffset dx="9" dy="10"></feOffset>
          <feGaussianBlur stdDeviation="1"></feGaussianBlur>
          <feComposite in2="hardAlpha" operator="out"></feComposite>
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.0705882 0 0 0 0 0.14902 0 0 0 0 0.85098 0 0 0 0.5 0"
          ></feColorMatrix>
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_23_50"
          ></feBlend>
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_23_50"
            result="shape"
          ></feBlend>
        </filter>
      </defs>
    </svg>
  );
}
