import type { QwikIntrinsicElements } from "@builder.io/qwik";

/***************************************************
 * Generated by SVG Artista on 5/24/2023, 9:59:33 AM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

//  svg .svg-elem-1 {
//   stroke-dashoffset: 75.5px;
//   stroke-dasharray: 75.5px;
//   -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s;
//           transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s;
// }

// svg.active .svg-elem-1 {
//   stroke-dashoffset: 0;
// }

// svg .svg-elem-2 {
//   stroke-dashoffset: 258.7503967285156px;
//   stroke-dasharray: 258.7503967285156px;
//   -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s;
//           transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s;
// }

// svg.active .svg-elem-2 {
//   stroke-dashoffset: 0;
// }


export function HUDtextHolder(
  props: QwikIntrinsicElements["svg"],
  key: string
) {
  return (
    <svg
      viewBox="0 0 226 93"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
      key={key}
    >
      <g filter="url(#filter0_d_26_64)">
        <path
          d="M0.5 1.5H5M9.5 1.5H43M168.5 80.5H201.5M210.5 80.5H213"
          stroke="#73E5FE"
          stroke-width="2"
          class="svg-elem-1"
        ></path>
      </g>
      <g filter="url(#filter1_d_26_64)">
        <path
          d="M1 1.5H44.8565C45.565 1.5 46.2207 1.87488 46.5801 2.48548L91.9199 79.5145C92.2793 80.1251 92.935 80.5 93.6435 80.5H213"
          stroke="#73E5FE"
          stroke-linecap="round"
          class="svg-elem-2"
        ></path>
      </g>
      <defs>
        <filter
          id="filter0_d_26_64"
          x="0.5"
          y="0.5"
          width="224.5"
          height="92"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood flood-opacity="0" result="BackgroundImageFix"></feFlood>
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          ></feColorMatrix>
          <feOffset dx="10" dy="9"></feOffset>
          <feGaussianBlur stdDeviation="1"></feGaussianBlur>
          <feComposite in2="hardAlpha" operator="out"></feComposite>
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.0705882 0 0 0 0 0.14902 0 0 0 0 0.85098 0 0 0 0.25 0"
          ></feColorMatrix>
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_26_64"
          ></feBlend>
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_26_64"
            result="shape"
          ></feBlend>
        </filter>
        <filter
          id="filter1_d_26_64"
          x="0.5"
          y="1"
          width="225"
          height="91"
          filterUnits="userSpaceOnUse"
          color-interpolation-filters="sRGB"
        >
          <feFlood flood-opacity="0" result="BackgroundImageFix"></feFlood>
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          ></feColorMatrix>
          <feOffset dx="10" dy="9"></feOffset>
          <feGaussianBlur stdDeviation="1"></feGaussianBlur>
          <feComposite in2="hardAlpha" operator="out"></feComposite>
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.0705882 0 0 0 0 0.14902 0 0 0 0 0.85098 0 0 0 0.25 0"
          ></feColorMatrix>
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_26_64"
          ></feBlend>
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_26_64"
            result="shape"
          ></feBlend>
        </filter>
      </defs>
    </svg>
  );
}
