import type { QwikIntrinsicElements } from "@builder.io/qwik";

/***************************************************
 * Generated by SVG Artista on 5/23/2023, 4:40:57 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

/***************************************************
 * Generated by SVG Artista on 5/23/2023, 5:28:40 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

/***************************************************
 * Generated by SVG Artista on 5/23/2023, 5:35:25 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

//  @-webkit-keyframes animate-svg-stroke-1 {
//   0% {
//     stroke-dashoffset: 336.3434753417969px;
//     stroke-dasharray: 336.3434753417969px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 336.3434753417969px;
//   }
// }

// @keyframes animate-svg-stroke-1 {
//   0% {
//     stroke-dashoffset: 336.3434753417969px;
//     stroke-dasharray: 336.3434753417969px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 336.3434753417969px;
//   }
// }

// .svg-elem-1 {
//   -webkit-animation: animate-svg-stroke-1 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both;
//           animation: animate-svg-stroke-1 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both;
// }

// @-webkit-keyframes animate-svg-stroke-2 {
//   0% {
//     stroke-dashoffset: 900.15771484375px;
//     stroke-dasharray: 900.15771484375px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 900.15771484375px;
//   }
// }

// @keyframes animate-svg-stroke-2 {
//   0% {
//     stroke-dashoffset: 900.15771484375px;
//     stroke-dasharray: 900.15771484375px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 900.15771484375px;
//   }
// }

// .svg-elem-2 {
//   -webkit-animation: animate-svg-stroke-2 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both;
//           animation: animate-svg-stroke-2 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both;
// }

// @-webkit-keyframes animate-svg-stroke-3 {
//   0% {
//     stroke-dashoffset: 479.57672119140625px;
//     stroke-dasharray: 479.57672119140625px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 479.57672119140625px;
//   }
// }

// @keyframes animate-svg-stroke-3 {
//   0% {
//     stroke-dashoffset: 479.57672119140625px;
//     stroke-dasharray: 479.57672119140625px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 479.57672119140625px;
//   }
// }

// .svg-elem-3 {
//   -webkit-animation: animate-svg-stroke-3 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both;
//           animation: animate-svg-stroke-3 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both;
// }


export function HUDMiddleLeft(props: QwikIntrinsicElements["svg"], key: string) {
  return (
    <svg
      width="258"
      height="638"
      viewBox="0 0 258 638"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
      key={key}
    >
      <path
        d="M206.126 599.521C174.119 584.392 145.035 562.217 120.534 534.259M43.25 321.342C43.25 281.798 50.0757 242.642 63.3367 206.109M120.534 108.426C145.035 80.4681 174.119 58.2927 206.126 43.1642"
        stroke="#73E5FE"
        class="svg-elem-1"
      ></path>
      <path
        d="M257.428 637.364C213.933 632.047 187.284 615.537 187.284 615.537C154.209 599.371 124.156 575.676 98.8395 545.802C73.523 515.928 59.8685 497.367 46.166 458.332L24.4184 453.014C-6.65126 344.744 -4.2707 285.54 24.4184 181.805L50.8262 171.17C64.5287 132.134 73.523 120.663 98.8395 90.7896C124.156 60.9158 154.21 37.2203 187.284 21.0544C187.284 21.0544 209.272 6.31781 257.428 1"
        stroke="#73E5FE"
        stroke-width="1"
        class="svg-elem-2"
      ></path>
      <path
        d="M84.7739 107C68.4968 128.258 62.1673 140.074 52.8438 166.192C51.8409 169.001 49.652 171.245 46.8498 172.268C39.8267 174.832 33.8512 176.98 27.805 179.725C25.2175 180.9 23.3312 183.243 22.5877 185.986C-4.95759 287.594 -7.14489 347.636 21.8344 447.919C22.434 449.993 23.6607 451.927 25.5554 452.964C29.3377 455.033 32.728 455.11 40.0498 455.893C43.8588 456.3 47.0239 458.963 48.2494 462.593C56.8643 488.106 64.5011 504.6 83.2731 526.644"
        stroke="#73E5FE"
        stroke-width="2.5"
        stroke-linecap="round"
        class="svg-elem-3"
      ></path>
    </svg>
  );
}
