import type { QwikIntrinsicElements } from "@builder.io/qwik";

/***************************************************
 * Generated by SVG Artista on 5/23/2023, 4:40:57 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

/***************************************************
 * Generated by SVG Artista on 5/23/2023, 5:28:40 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

//  @-webkit-keyframes animate-svg-stroke-1 {
//   0% {
//     stroke-dashoffset: 890.3394165039062px;
//     stroke-dasharray: 890.3394165039062px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 890.3394165039062px;
//   }
// }

// @keyframes animate-svg-stroke-1 {
//   0% {
//     stroke-dashoffset: 890.3394165039062px;
//     stroke-dasharray: 890.3394165039062px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 890.3394165039062px;
//   }
// }

// .svg-elem-1 {
//   -webkit-animation: animate-svg-stroke-1 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both;
//           animation: animate-svg-stroke-1 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both;
// }

// @-webkit-keyframes animate-svg-stroke-2 {
//   0% {
//     stroke-dashoffset: 900.158447265625px;
//     stroke-dasharray: 900.158447265625px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 900.158447265625px;
//   }
// }

// @keyframes animate-svg-stroke-2 {
//   0% {
//     stroke-dashoffset: 900.158447265625px;
//     stroke-dasharray: 900.158447265625px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 900.158447265625px;
//   }
// }

// .svg-elem-2 {
//   -webkit-animation: animate-svg-stroke-2 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both;
//           animation: animate-svg-stroke-2 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both;
// }

// @-webkit-keyframes animate-svg-stroke-3 {
//   0% {
//     stroke-dashoffset: 479.57769775390625px;
//     stroke-dasharray: 479.57769775390625px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 479.57769775390625px;
//   }
// }

// @keyframes animate-svg-stroke-3 {
//   0% {
//     stroke-dashoffset: 479.57769775390625px;
//     stroke-dasharray: 479.57769775390625px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 479.57769775390625px;
//   }
// }

// .svg-elem-3 {
//   -webkit-animation: animate-svg-stroke-3 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both;
//           animation: animate-svg-stroke-3 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both;
// }

// @-webkit-keyframes animate-svg-stroke-4 {
//   0% {
//     stroke-dashoffset: 127.82252502441406px;
//     stroke-dasharray: 127.82252502441406px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 127.82252502441406px;
//   }
// }

// @keyframes animate-svg-stroke-4 {
//   0% {
//     stroke-dashoffset: 127.82252502441406px;
//     stroke-dasharray: 127.82252502441406px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 127.82252502441406px;
//   }
// }

// .svg-elem-4 {
//   -webkit-animation: animate-svg-stroke-4 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s both;
//           animation: animate-svg-stroke-4 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s both;
// }

// @-webkit-keyframes animate-svg-stroke-5 {
//   0% {
//     stroke-dashoffset: 222.1090850830078px;
//     stroke-dasharray: 222.1090850830078px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 222.1090850830078px;
//   }
// }

// @keyframes animate-svg-stroke-5 {
//   0% {
//     stroke-dashoffset: 222.1090850830078px;
//     stroke-dasharray: 222.1090850830078px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 222.1090850830078px;
//   }
// }

// .svg-elem-5 {
//   -webkit-animation: animate-svg-stroke-5 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s both;
//           animation: animate-svg-stroke-5 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s both;
// }


export function HUDMiddleRight(props: QwikIntrinsicElements["svg"], key: string) {
  return (
    <svg
      width="565"
      height="638"
      viewBox="0 0 565 638"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
      key={key}
    >
      <path
        d="M264.077 15.0665C298.719 15.0665 333.022 22.8524 365.028 37.9809C397.035 53.1094 426.12 75.2847 450.62 103.242C475.12 131.2 494.557 164.393 507.818 200.926C521.079 237.458 527.904 276.615 527.904 316.159C527.904 355.703 521.079 394.86 507.818 431.393C494.557 467.925 475.12 501.118 450.62 529.076C426.12 557.033 397.035 579.209 365.028 594.337C333.022 609.466 298.718 617.251 264.077 617.251"
        stroke="#73E5FE"
        stroke-width="1"
        class="svg-elem-1"
      ></path>
      <path
        d="M307.572 0.63562C351.067 5.95343 377.716 22.4626 377.716 22.4626C410.791 38.6285 440.844 62.3241 466.161 92.1979C491.477 122.072 505.132 140.633 518.834 179.668L540.582 184.986C571.651 293.256 569.271 352.46 540.582 456.195L514.174 466.83C500.471 505.866 491.477 517.337 466.16 547.21C440.844 577.084 410.79 600.78 377.716 616.946C377.716 616.946 355.728 631.682 307.572 637"
        stroke="#73E5FE"
        stroke-width="1"
        class="svg-elem-2"
      ></path>
      <path
        d="M479.999 530.644C496.276 509.386 502.606 497.57 511.929 471.452C512.932 468.642 515.121 466.399 517.923 465.376C524.946 462.812 530.922 460.663 536.968 457.919C539.556 456.744 541.442 454.401 542.185 451.658C569.731 350.05 571.918 290.007 542.939 189.725C542.339 187.65 541.112 185.717 539.218 184.68C535.435 182.611 532.045 182.533 524.723 181.751C520.914 181.344 517.749 178.681 516.524 175.051C507.909 149.537 500.272 133.043 481.5 111"
        stroke="#73E5FE"
        stroke-width="2.5"
        stroke-linecap="round"
        class="svg-elem-3"
      ></path>
      <path
        d="M264.077 27.2247V15.5001C300.604 14.8209 329.002 18.3363 373.5 42"
        stroke="#73E5FE"
        stroke-width="2.5"
        stroke-linecap="round"
        class="svg-elem-4"
      ></path>
      <path
        d="M510 208.5C522.5 235.5 545.5 335 510 424"
        stroke="#73E5FE"
        stroke-width="2"
        stroke-linecap="round"
        class="svg-elem-5"
      ></path>
    </svg>
  );
}
