import type { QwikIntrinsicElements } from "@builder.io/qwik";

/***************************************************
 * Generated by SVG Artista on 5/23/2023, 5:09:53 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

//  @-webkit-keyframes animate-svg-stroke-1 {
//   0% {
//     stroke-dashoffset: 75.5px;
//     stroke-dasharray: 75.5px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 75.5px;
//   }
// }

// @keyframes animate-svg-stroke-1 {
//   0% {
//     stroke-dashoffset: 75.5px;
//     stroke-dasharray: 75.5px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 75.5px;
//   }
// }

// .svg-elem-1 {
//   -webkit-animation: animate-svg-stroke-1 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both;
//           animation: animate-svg-stroke-1 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both;
// }

// @-webkit-keyframes animate-svg-stroke-2 {
//   0% {
//     stroke-dashoffset: 258.7503967285156px;
//     stroke-dasharray: 258.7503967285156px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 258.7503967285156px;
//   }
// }

// @keyframes animate-svg-stroke-2 {
//   0% {
//     stroke-dashoffset: 258.7503967285156px;
//     stroke-dasharray: 258.7503967285156px;
//   }

//   100% {
//     stroke-dashoffset: 0;
//     stroke-dasharray: 258.7503967285156px;
//   }
// }

// .svg-elem-2 {
//   -webkit-animation: animate-svg-stroke-2 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both;
//           animation: animate-svg-stroke-2 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both;
// }


export function HUDtextHolder(props: QwikIntrinsicElements["svg"], key: string) {
  return (
    <svg
      viewBox="0 0 214 82"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
      key={key}
    >
      <path
        d="M0.5 1.5H5M9.5 1.5H43M168.5 80.5H201.5M210.5 80.5H213"
        stroke="#73E5FE"
        stroke-width="2"
        class="svg-elem-1"
      ></path>
      <path
        d="M1 1.5H44.8565C45.565 1.5 46.2207 1.87488 46.5801 2.48548L91.9199 79.5145C92.2793 80.1251 92.935 80.5 93.6435 80.5H213"
        stroke="#73E5FE"
        stroke-width="0.5"
        stroke-linecap="round"
        class="svg-elem-2"
      ></path>
    </svg>
  );
}
